using System.Text;

namespace Loadout.Core.Instructions;

/// <summary>
/// A starting point for publishing the generated documents from CI.
/// </summary>
/// <remarks>
/// <para>
/// A starting point and said to be one. This writes a GitHub Actions workflow
/// because that is what most repositories here use, and a workflow file dates:
/// action versions move, runner images change, and the syntax is not this
/// project's to keep up with. The skill that ships beside it is what adapts
/// this to whatever CI a repository actually has, and to the ones this cannot
/// write at all.
/// </para>
/// <para>
/// The user guide is excluded, and that is the important line in the file. It
/// is emitted as a scaffold precisely so nobody mistakes it for documentation;
/// a pipeline that published it unreviewed every night would undo the whole
/// reason for marking it. Somebody who wants it published has to say so, having
/// read it.
/// </para>
/// </remarks>
public static class DocsWorkflow
{
    /// <summary>Writes a workflow that regenerates the documents on every push.</summary>
    /// <param name="projectSlug">The project to document.</param>
    /// <param name="outputDirectory">Where the documents should land in the repository.</param>
    /// <param name="frontMatter">Whether to ask for the static-site header.</param>
    /// <param name="includeUserGuide">
    /// Whether to publish the scaffold. False unless somebody has read it and
    /// decided otherwise.
    /// </param>
    public static string GitHubActions(
        string projectSlug,
        string outputDirectory = "docs/generated",
        bool frontMatter = true,
        bool includeUserGuide = false)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectSlug);

        var directory = outputDirectory.Replace('\\', '/').TrimEnd('/');

        var text = new StringBuilder()
            .AppendLine("# Generated by 'loadout docs ci'. A starting point, not a fixture:")
            .AppendLine("# action versions move and runner images change, and neither is")
            .AppendLine("# Loadout's to keep up with. Adapt it and commit your version.")
            .AppendLine("name: documentation")
            .AppendLine()
            .AppendLine("on:")
            .AppendLine("  push:")
            .AppendLine("    branches: [main]")
            .AppendLine("  workflow_dispatch:")
            .AppendLine()
            .AppendLine("jobs:")
            .AppendLine("  generate:")
            .AppendLine("    runs-on: ubuntu-latest")
            .AppendLine("    steps:")
            .AppendLine("      - uses: actions/checkout@v4")
            .AppendLine()
            .AppendLine("      # Loadout has to be on PATH and the project registered before")
            .AppendLine("      # any of this runs. How that happens is yours: a released")
            .AppendLine("      # binary, a build from source, or a container.")
            .AppendLine("      - name: Write the documents")
            .AppendLine("        run: |")
            .AppendLine($"          mkdir -p {directory}");

        foreach (var (type, file, wantsHeader) in Published(includeUserGuide))
        {
            // Per document rather than per run. The machine index is read by a
            // model, not rendered by a site generator: a YAML header on it is
            // noise in the one file whose whole purpose is to say where things
            // are in as few tokens as possible.
            var flag = frontMatter && wantsHeader ? " --front-matter" : string.Empty;

            text.AppendLine(
                $"          loadout docs export --type {type} --project {projectSlug}{flag} \\")
                .AppendLine($"            --out {directory}/{file}");
        }

        if (!includeUserGuide)
        {
            text.AppendLine()
                .AppendLine("      # The user guide is deliberately not generated here. It is a")
                .AppendLine("      # scaffold: headings from the shape of the code, with the")
                .AppendLine("      # parts a reader actually wants left as TODO. Publishing it")
                .AppendLine("      # unreviewed would give somebody a document that reads like")
                .AppendLine("      # documentation and teaches them nothing. Write it once by")
                .AppendLine("      # hand, commit it, and let this pipeline leave it alone.");
        }

        text.AppendLine()
            .AppendLine("      - name: Say what changed")
            .AppendLine("        run: git --no-pager diff --stat")
            .AppendLine()
            .AppendLine("      # Committing the result, opening a pull request or publishing to")
            .AppendLine("      # a site is left to you on purpose: each of those writes")
            .AppendLine("      # somewhere, and what to write to is a decision about your")
            .AppendLine("      # repository rather than a default worth guessing.");

        return text.ToString();
    }

    /// <summary>
    /// Which documents a pipeline should write, to what file, and whether the
    /// site generator's header belongs on them.
    /// </summary>
    /// <remarks>
    /// The machine index does not take a header. It is read by a model rather
    /// than rendered by a site, and its whole purpose is to say where things
    /// are in as few tokens as possible — a YAML preamble is the opposite of
    /// that. It is also named llms.txt rather than .md for the same reason:
    /// the convention it follows is not a page.
    /// </remarks>
    internal static IReadOnlyList<(string Type, string File, bool WantsHeader)> Published(
        bool includeUserGuide)
    {
        var published = new List<(string, string, bool)>
        {
            ("reference", "reference.md", true),
            ("technical", "architecture.md", true),
            ("machine-index", "llms.txt", false),
        };

        if (includeUserGuide)
        {
            published.Insert(0, ("user-guide", "guide.md", true));
        }

        return published;
    }
}
